version: '3.9'
services:
  StreetEats-db:
    container_name: StreetEats-db
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_streeteats:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: StreetEats
      POSTGRES_PASSWORD: staEteertS
    restart: always

volumes:
  postgres_data_streeteats:
