version: '3.9'

services:
  redis:
    container_name: portfolio-redis
    image: redis
    ports:
      - "6378:6379"
    restart: always

  portfolio-db:
    container_name: portfolio-db
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio
      POSTGRES_PASSWORD: portfolio
    restart: always

volumes:
  portfolio_postgres_data:
